import Link from 'next/link';
import Image from 'next/image';
import {MDXRemote} from 'next-mdx-remote/rsc';
import {getStories,getArchive,storyHref,type ArchiveItem} from '@/lib/edition/content';
import {categoryNames,dateText,type Locale,type Story,type Category} from '@/lib/edition/types';
import Subscribe from './Subscribe';
import {issues} from '@/lib/issues';
import {ArticleActions,SavedList} from './Controls';
import ThaiFrontRow from './ThaiFrontRow';
const t=(l:Locale,en:string,zh:string)=>l==='en'?en:zh;
function Kicker({children}:{children:React.ReactNode}){return <div className="ed-kicker">{children}</div>}
export function StoryImage({s,l,priority=false}:{s:Story;l:Locale;priority?:boolean}){return s.image?<Image src={s.image} alt={s.alt?.[l]||s.title[l]} width={960} height={1280} sizes="(max-width: 700px) 100vw, 50vw" priority={priority}/>:<div className={`ed-type-cover${s.coverTone?` ed-type-cover--${s.coverTone}`:''}`} aria-hidden="true"><span>C33</span><em>{s.coverLabel?.[l]||(s.slug==='tres-parisien-in-print'?'Très\nParisien':s.slug==='after-quiet-luxury'?'Quiet,\nplease.':'Ways of\nseeing.')}</em><small>{s.tag} / {s.date.slice(0,4)}</small></div>}
export function Card({s,l}:{s:Story;l:Locale}){return <article className="ed-card"><Link href={storyHref(s,l)} className="ed-card-image" tabIndex={-1} aria-hidden="true"><StoryImage s={s} l={l}/></Link><Kicker>{categoryNames[s.category][l]}{s.tag!=='PEOPLE'&&<span> · {s.tag}</span>}</Kicker><h3><Link href={storyHref(s,l)}>{s.title[l]}</Link></h3><p>{s.summary[l]}</p><time dateTime={s.date}>{dateText(s.date,l)}</time></article>}
function SectionTitle({title,href,label}:{title:string;href?:string;label?:string}){return <div className="ed-section-title"><h2>{title}</h2>{href&&<Link href={href}>{label} ↗</Link>}</div>}
type TopicId='milan-ss27'|'paris-ss27';
function topicDetails(topic:TopicId,l:Locale){return topic==='paris-ss27'?{name:t(l,'Paris Fashion Week','巴黎时装周'),description:t(l,'Spring/Summer 2027. Collection reviews from the Paris runway.','2027 春夏。沿着秀场造型阅读巴黎系列。'),intro:t(l,'Collection notes on Courrèges, Chloé, Valentino, Mugler, Shiatzy Chen and Louis Vuitton, each focused on the clothes.','收录 Courrèges、Chloé、Valentino、Mugler、夏姿·陈与 Louis Vuitton 的系列观察，逐篇细看衣服。'),dates:'30 / 09 – 06 / 10 / 2026',image:'/images/edition/chloe-ss27-32.jpg',alt:t(l,'Red rain cape from Chloé Spring 2027','Chloé 2027 春夏红色雨披')}: {name:t(l,'Milan Fashion Week','米兰时装周'),description:t(l,'Spring/Summer 2027. Collections and the people around them.','2027 春夏。收录系列观察与人物报道。'),intro:t(l,'Collection notes on Marni, Gucci, Bottega Veneta and Loro Piana, with looks from Becky Armstrong, Billkin, PP Krit and Song Weilong.','从 Marni、Gucci、Bottega Veneta 与 Loro Piana 的系列，到 Becky Armstrong、Billkin、PP Krit 和宋威龙的造型。'),dates:'23–27 / 09 / 2026',image:'/images/edition/marni-03.jpg',alt:t(l,'Marni runway look','Marni 秀场造型')};}
export function TopicCard({l,topic='paris-ss27'}:{l:Locale;topic?:TopicId}){const count=getStories().filter(s=>s.topic===topic).length,d=topicDetails(topic,l);return <Link href={`/${l}/topics/${topic}`} className="ed-topic-card"><div><Kicker>{t(l,`THE DOSSIER / ${count} STORIES`,`专题／${count} 篇文章`)}</Kicker><h2>{d.name}</h2><p>{d.description}</p><span>{t(l,'Explore the dossier','进入专题')} ↗</span></div><Image src={d.image} alt={d.alt} width={600} height={800} sizes="(max-width:700px) 40vw, 30vw"/></Link>}
function HomeIssues({l}:{l:Locale}){return <section className="ed-section ed-home-issues" aria-labelledby="home-issues"><div className="ed-section-title"><h2 id="home-issues">{t(l,'C33 issues','C33 期刊')}</h2><Link href={`/${l}/issues`}>{t(l,'View all issues','查看全部期刊')} ↗</Link></div><div className="ed-issue-pair">{[...issues].filter(i=>i.status!=='upcoming').sort((a,b)=>b.number.localeCompare(a.number)).map(i=><article key={i.slug} className="ed-home-issue"><Link href={`/issue/${i.slug}`} aria-label={t(l,`Open issue ${i.number}`,`阅读第 ${i.number} 期`)}><Image src={i.cover!} alt={`C33 N°${i.number} · ${i.title}`} width={600} height={800} sizes="(max-width:600px) 42vw, 22vw"/></Link><div><Kicker>N° {i.number} · {i.number==='02'?t(l,'SUMMER 2026','2026 夏'):t(l,'SPRING 2026','2026 春')}</Kicker><h3>{i.title.split(' / ')[l==='en'?0:1]}</h3><p>{i.number==='02'?t(l,'Fashion, place and the changing influence of brands.','秀场、城市与品牌影响力的变化。'):t(l,'The people, craft and images behind fashion.','从人物、工艺与影像，看时尚如何被塑造。')}</p><Link className="ed-issue-read" href={`/issue/${i.slug}`}>{t(l,'Read this issue','阅读本期')} ↗</Link><small>{t(l,'Original edition in Chinese and French','中文／法文原刊')}</small></div></article>)}</div></section>}
export function Home({l}:{l:Locale}){const all=getStories(),lead=all[0];return <>
 <div className="ed-dateline"><span>{t(l,'THE EDIT','本期精选')}</span><Link href={storyHref(lead,l)}>{t(l,'Fashion month · Spring/Summer 2027','时装月 · 2027 春夏')} ↗</Link></div>
 <section className="ed-lead"><div className="ed-lead-image"><Link href={storyHref(lead,l)} aria-label={lead.title[l]}><StoryImage s={lead} l={l} priority/></Link>{lead.image&&lead.credit&&<span className="ed-photo-credit">{lead.credit[l]}</span>}</div><div className="ed-lead-copy"><Kicker>{categoryNames[lead.category][l]} / {lead.tag}</Kicker><h1><Link href={storyHref(lead,l)}>{lead.title[l]}</Link></h1><p>{lead.summary[l]}</p><Link className="ed-read" href={storyHref(lead,l)}>{t(l,'Read the story','阅读全文')} ↗</Link><div className="ed-next"><Kicker>{t(l,'ALSO IN THIS EDIT','同时阅读')}</Kicker><Link href={storyHref(all[1],l)}>{all[1].title[l]} ↗</Link></div></div></section>
 <HomeIssues l={l}/>
 <section className="ed-section"><SectionTitle title={t(l,'Latest additions','最新收录')} href={`/${l}/search`} label={t(l,'All stories','全部文章')}/><div className="ed-grid">{all.filter(x=>x.slug!==lead.slug&&x.slug!=='after-quiet-luxury'&&x.slug!=='two-windows').slice(0,3).map(s=><Card key={s.slug} s={s} l={l}/>)}</div></section>
 <section className="ed-section"><TopicCard l={l}/><div className="ed-topic-more"><Link href={`/${l}/topics/milan-ss27`}>{t(l,'Milan Fashion Week dossier','米兰时装周专题')} ↗</Link></div></section>
 <section className="ed-section" aria-labelledby="home-archive-heading"><div className="ed-section-title"><h2 id="home-archive-heading">{t(l,'More to read','更多阅读')}</h2><Link href={`/${l}/archive`}>{t(l,'All articles','查看全部文章')} ↗</Link></div><div className="ed-list">{(['after-quiet-luxury','two-windows'] as const).map((slug,i)=>{const s=all.find(item=>item.slug===slug)!;return <article key={s.slug}><span className="ed-index">0{i+1}</span><div><Kicker>{categoryNames[s.category][l]} / {t(l,'COMMENTARY','评论')}</Kicker><h3><Link href={storyHref(s,l)}>{s.title[l]}</Link></h3><p>{s.summary[l]}</p><a className="ed-original-link" href={s.original}>{t(l,'First-published version','首次发表版本')} ↗</a></div><time dateTime={s.date}>{dateText(s.date,l)}</time></article>})}</div></section>
 </>}
export function CategoryPage({l,category}:{l:Locale;category:Category}){const all=getStories().filter(s=>s.category===category);const descriptions={fashion:t(l,'Collections, clothes and the way they are seen.','系列、衣服，以及观看它们的方式。'),culture:t(l,'Images, ideas and the things we live with.','图像、观念与日常相伴之物。'),people:t(l,'People and the work, choices and clothes around them.','人物，以及他们的创作、选择和衣着。')};return <><header className="ed-page-title"><Kicker>C33</Kicker><h1>{categoryNames[category][l]}</h1><p>{descriptions[category]}</p></header><div className="ed-grid ed-section">{all.map(s=><Card key={s.slug} s={s} l={l}/>)}</div><section className="ed-section"><SectionTitle title={t(l,'More stories','更多文章')}/><ArchiveList items={getArchive().filter(a=>a.category===category)} l={l}/></section></>}
function Paragraphs({blocks}:{blocks:string[]}){return <>{blocks.map((p,i)=>p.startsWith('## ')?<h2 key={i} id={`section-${i}`}>{p.slice(3)}</h2>:<p key={i}>{p}</p>)}</>}
export function ReadPage({s,l}:{s:Story;l:Locale}){if(s.slug==='fashion-month-thai-front-row')return <ThaiFrontRow s={s} l={l}/>;const related=getStories().filter(x=>x.slug!==s.slug).sort((a,b)=>Number(b.category===s.category)-Number(a.category===s.category)).slice(0,3);return <article>
 <header className="ed-article-header"><Kicker><Link href={`/${l}/${s.category}`}>{categoryNames[s.category][l]}</Link> / {s.tag}</Kicker><h1>{s.title[l]}</h1><p className="ed-deck">{s.summary[l]}</p><div className="ed-byline"><span>{s.author?(s.author==='C33'?t(l,'Words & selection: C33','文字与选编：C33'):`${t(l,'By','作者：')} ${s.author}`):t(l,'No individual byline recorded','未标注个人作者')}</span><time dateTime={s.date}>{s.dateLabel?.[l]} {dateText(s.date,l)}</time>{s.updated&&<span>{t(l,'Edition updated','本版更新')} {dateText(s.updated,l)}</span>}</div><ArticleActions id={s.slug} locale={l}/></header>
 {s.image&&<figure className="ed-article-figure"><StoryImage s={s} l={l} priority/><figcaption>{s.credit?.[l]}</figcaption></figure>}
 <div className="ed-reading-layout"><aside className="ed-reading-aside"><Kicker>{t(l,'IN THIS STORY','本文内容')}</Kicker>{s.body[l].filter(p=>p.startsWith('## ')).map(p=><a key={p} href={`#section-${s.body[l].indexOf(p)}`}>{p.slice(3)}</a>)}{s.topic&&<Link href={`/${l}/topics/${s.topic}`}>{s.topic==='paris-ss27'?t(l,'Paris dossier','巴黎专题'):t(l,'Milan dossier','米兰专题')} ↗</Link>}</aside><div className="ed-prose">{s.note&&<div className="ed-note">{s.note[l]}</div>}<Paragraphs blocks={s.body[l]}/></div></div>
 {s.gallery&&<div className="ed-gallery">{s.gallery.map(g=><figure key={g.src}><Image src={g.src} alt={g.alt[l]} width={900} height={1200} sizes="(max-width:700px) 100vw, 45vw"/><figcaption>{g.alt[l]} · {s.credit?.[l]}</figcaption></figure>)}</div>}
 <section className="ed-sources"><h2>{t(l,'Sources & further reading','来源与延伸阅读')}</h2><ul>{s.sources.map((x,i)=><li key={i}><a href={x.url}>{typeof x.label==='string'?x.label:x.label[l]} ↗</a></li>)}</ul>{s.original&&<a href={s.original}>{t(l,'View the original publication','查看原始发布')} ↗</a>}</section><section className="ed-section"><SectionTitle title={t(l,'Keep reading','相关阅读')}/><div className="ed-grid">{related.map(x=><Card key={x.slug} s={x} l={l}/>)}</div></section>
 </article>}
export function ArchiveList({items,l}:{items:ArchiveItem[];l:Locale}){return <div className="ed-archive-list">{items.map(a=><article key={a.slug}><div><Kicker>{categoryNames[a.category][l]} / {a.type==='journal'?'JOURNAL':t(l,'ARTICLE','文章')}</Kicker><h3><Link href={`/${l}/archive/${a.slug}`}>{a.title[l]}</Link></h3><p>{a.summary[l]}</p><small>{a.fullTranslation?t(l,'A bilingual reading edition is available','已有双语阅读版'):t(l,'Chinese original · English body translation pending','中文原文 · 英文全文待译')}</small></div><time dateTime={a.date}>{dateText(a.date,l)}</time></article>)}</div>}
export function ArchivePage({l}:{l:Locale}){return <><header className="ed-page-title"><Kicker>C33 / 26</Kicker><h1>{t(l,'All articles','文章目录')}</h1><p>{t(l,'Twenty articles and six Journal notes, listed by their first publication dates.','20 篇文章与 6 篇 Journal 短文，按首次发表日期排列。')}</p></header><ArchiveList items={getArchive()} l={l}/></>}
export function ArchiveRead({a,l}:{a:ArchiveItem;l:Locale}){return <article><header className="ed-article-header"><Kicker>{categoryNames[a.category][l]} / {a.type==='journal'?'JOURNAL':t(l,'ARTICLE','文章')}</Kicker><h1>{a.title[l]}</h1><p className="ed-deck">{a.summary[l]}</p><div className="ed-byline"><span>{a.author||t(l,'No individual byline recorded','未标注个人作者')}</span><time dateTime={a.date}>{dateText(a.date,l)}</time></div><ArticleActions id={`archive:${a.slug}`} locale={l}/></header><div className="ed-prose ed-archive-prose"><div className="ed-note">{t(l,'This page preserves the published text. Some sources, names, dates and image credits have yet to be independently checked.','本页保留首次发表的正文；部分来源、人名、日期及图片署名仍待核对。')}{l==='en'&&!a.fullTranslation&&<p>Full English translation is pending. The Chinese original follows, with an English catalogue title and summary above.</p>} {a.fullTranslation&&<p><Link href={`/${l}/read/${a.fullTranslation}`}>{t(l,'Read the complete bilingual edition','阅读完整双语版本')} ↗</Link></p>}<p><a href={a.original}>{t(l,'First-published page','首次发表页面')} ↗</a></p></div><div lang="zh-CN"><MDXRemote source={a.body}/></div></div><section className="ed-sources"><Link href={`/${l}/archive`}>← {t(l,'All articles','返回文章目录')}</Link></section></article>}
export function TopicPage({l,index=false,topic='paris-ss27'}:{l:Locale;index?:boolean;topic?:TopicId}){const d=topicDetails(topic,l);return <><header className="ed-page-title"><Kicker>{t(l,'THE DOSSIERS','专题')}</Kicker><h1>{index?t(l,'Topics','专题'):d.name}</h1><p>{index?t(l,'Follow a subject across several stories.','沿着一个主题，阅读彼此相关的文章。'):d.description}</p></header>{index?<div className="ed-section ed-topics-list"><TopicCard l={l} topic="paris-ss27"/><TopicCard l={l} topic="milan-ss27"/></div>:<><div className="ed-topic-intro"><p>{d.intro}</p><span>{d.dates}</span></div><div className="ed-grid ed-section">{getStories().filter(s=>s.topic===topic).map(s=><Card key={s.slug} s={s} l={l}/>)}</div></>}</>}
export function SearchPage({l,q}:{l:Locale;q:string}){const term=q.trim().toLocaleLowerCase();const storyMatches=getStories().filter(s=>!term||JSON.stringify([s.title,s.summary,s.body,s.category]).toLocaleLowerCase().includes(term));const archiveMatches=getArchive().filter(a=>!term||JSON.stringify([a.title,a.summary,a.body,a.category]).toLocaleLowerCase().includes(term));return <><header className="ed-page-title"><Kicker>C33</Kicker><h1>{t(l,'Find a story','查找文章')}</h1><form className="ed-search" action={`/${l}/search`}><label className="sr-only" htmlFor="q">{t(l,'Search titles and article text','搜索标题与正文')}</label><input id="q" name="q" defaultValue={q} placeholder={t(l,'Try Marni, cinema, 宋威龙…','试试 Marni、电影、宋威龙…')}/><button>{t(l,'Search','搜索')} ↗</button></form><p role="status">{storyMatches.length+archiveMatches.length} {t(l,'results','条结果')}</p></header>{storyMatches.length>0&&<div className="ed-grid ed-section">{storyMatches.map(s=><Card key={s.slug} s={s} l={l}/>)}</div>}{archiveMatches.length>0&&<section className="ed-section"><SectionTitle title={t(l,'Other articles','其他文章')}/><ArchiveList items={archiveMatches} l={l}/></section>}{!storyMatches.length&&!archiveMatches.length&&<div className="ed-section"><p>{t(l,'No matching stories. Try a name, brand or a shorter phrase.','没有找到相关文章。可以试试人名、品牌名或更短的关键词。')}</p><Link href={`/${l}/archive`}>{t(l,'All articles','查看全部文章')} ↗</Link></div>}</>}
export function SavedPage({l}:{l:Locale}){const items=[...getStories().map(s=>({id:s.slug,title:s.title[l],href:storyHref(s,l)})),...getArchive().map(a=>({id:`archive:${a.slug}`,title:a.title[l],href:`/${l}/archive/${a.slug}`}))];return <><header className="ed-page-title"><Kicker>C33</Kicker><h1>{t(l,'Your reading list','你的收藏')}</h1><p>{t(l,'Saved in this browser, without an account. English and Chinese share the same list.','收藏保存在当前浏览器，无需账号，中英文共用同一份列表。')}</p></header><section className="ed-section"><SavedList items={items} locale={l}/></section></>}
export function InfoPage({l,page}:{l:Locale;page:string}){const en=l==='en';if(page==='about')return <><header className="ed-page-title"><Kicker>ABOUT / C33</Kicker><h1>{t(l,'About C33','关于 C33')}</h1></header><div className="ed-prose ed-info"><p className="ed-intro">{t(l,'C33 is an independent magazine covering fashion, art and culture.','C33 是一本关注时尚、艺术与文化的独立刊物。')}</p><p>{t(l,'We publish news, interviews, photography and commentary on the people and work behind them.','我们通过新闻、访谈、摄影与评论，关注这些领域中的人物与创作。')}</p><p>{t(l,'Our subjects can also take us into film, music, design and everyday life. The website and Instagram share a visual identity; each story is edited for the place where it will be read.','选题也可以延伸至电影、音乐、设计与日常生活。网站与 Instagram 共用视觉风格，每篇内容分别按平台的阅读方式编辑。')}</p></div></>;
 if(page==='contact')return <><header className="ed-page-title"><Kicker>C33</Kicker><h1>{t(l,'Keep in touch.','保持联系。')}</h1><p>{t(l,'Editorial enquiries, submissions and collaborations.','编辑咨询、投稿与合作。')}</p></header><div className="ed-prose ed-info"><h2>{t(l,'Write to us','写信给我们')}</h2><a href="mailto:contact@c33zine.com">contact@c33zine.com</a><p>{t(l,'For a story proposal, tell us the subject, your angle and the material you already have. Include relevant sources and image credits.','如果你希望投稿，请说明选题、切入角度及已有素材，并附相关来源和图片署名。')}</p><h2 id="subscribe">{t(l,'Subscribe to C33','订阅 C33')}</h2><p>{t(l,'Receive new stories and magazine updates by email.','通过邮件接收新文章与刊物消息。')}</p><Subscribe locale={l}/><h2>Instagram</h2><a href="https://www.instagram.com/c33zine/">@c33zine ↗</a></div></>;
 if(page==='issues')return <><header className="ed-page-title"><Kicker>C33</Kicker><h1>{t(l,'The issues','期刊档案')}</h1><p>{t(l,'The original issue pages remain available in Chinese and French.','保留原有中法文期刊页面。')}</p></header><div className="ed-issues">{[['02','Le déplacement','位移','Summer 2026','2026 夏'],['01','La fabrique','制造','Spring 2026','2026 春']].map(([id,title,zh,date,cn])=><a href={`/issue/${id}`} key={id}><Image src={`/images/issue-${id}-v2.jpg`} alt={`C33 ${id}`} width={600} height={800}/><h2>N° {id} · {en?title:zh}</h2><p>{en?date:cn}</p><small>{t(l,'Original issue · English translation pending','原始期刊 · 英文版本待译')} ↗</small></a>)}</div></>;
 return <><header className="ed-page-title"><Kicker>C33</Kicker><h1>{t(l,'Legal information','法律信息')}</h1></header><div className="ed-prose ed-info"><h2>{t(l,'Publisher','出版公司')}</h2><p>LUMEN ADVANCE<br/>{t(l,'Société par actions simplifiée (SAS)','法国简易股份公司（SAS）')}<br/>{t(l,'Share capital: €10,000','注册资本：10,000 欧元')}<br/>RCS Meaux 130 086 770<br/>{t(l,'Registered office','注册地址')}：30 boulevard Mendès France, 77600 Bussy-Saint-Georges, France</p><h2>{t(l,'Contact','联系')}</h2><a href="mailto:contact@c33zine.com">contact@c33zine.com</a><h2>{t(l,'Hosting','网站托管')}</h2><p>Vercel Inc., 440 N Barranca Ave #4133, Covina, CA 91723, USA.</p><h2>{t(l,'Content and images','内容与图片')}</h2><p>{t(l,'Image sources are listed with the relevant stories. Source attribution does not itself establish permission to reuse an image. Contact the publisher about reproduction.','图片来源随文章注明。来源署名本身不代表图片再使用授权；转载事宜请联系出版方。')}</p><h2>{t(l,'Privacy and local storage','隐私与本地存储')}</h2><p>{t(l,'Reading-list entries are stored locally in your browser. To ask about access, correction or deletion of personal information provided to C33, contact the email above.','文章收藏保存在你的浏览器中。如需查询、更正或删除提交给 C33 的个人信息，请通过上述邮箱联系。')}</p><p className="ed-note">{t(l,'The publication-director field remains unresolved in this review version.','本审阅版本的法定出版负责人信息仍待补齐。')}</p><a href="/mentions-legales">{t(l,'Existing French legal page','现有法文法律页面')} ↗</a></div></>;
}
