"use client";
import {useState} from 'react';
import type {Locale} from '@/lib/edition/types';
export default function Subscribe({locale}:{locale:Locale}){
 const en=locale==='en';const [email,setEmail]=useState('');const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);
 const endpoint=process.env.NEXT_PUBLIC_NEWSLETTER_ENDPOINT;
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;if(!endpoint){const subject=en?'C33 subscription request':'C33 订阅申请';const body=en?`Please send C33 stories and magazine updates to ${email}.`:`希望通过 ${email} 接收 C33 新文章和刊物消息。`;window.location.href=`mailto:contact@c33zine.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;setStatus(en?'Your email app will open. Send the message there to request a subscription. You are not subscribed yet.':'邮箱应用将打开。请在那里发送邮件申请订阅；目前尚未完成订阅。');return;}setBusy(true);try{const buttondown=endpoint.includes('buttondown.email');const res=await fetch(endpoint,buttondown?{method:'POST',mode:'no-cors',body:new URLSearchParams({email})}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});if(!buttondown&&!res.ok)throw Error();setStatus(en?'Request sent. Check your inbox for confirmation.':'请求已发送，请查看邮箱中的确认信息。');setEmail('');}catch{setStatus(en?'The request could not be sent. Please try again or email us.':'发送失败，请重试或通过邮件联系我们。');}finally{setBusy(false);}}
 return <div className="ed-subscription"><form onSubmit={submit}><label htmlFor="subscription-email">{en?'Email address':'电子邮箱'}</label><div><input id="subscription-email" type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} disabled={busy} placeholder="you@example.com"/><button disabled={busy}>{busy?(en?'Sending…':'发送中…'):(endpoint?(en?'Subscribe':'订阅'):(en?'Request by email':'通过邮件申请'))} ↗</button></div></form><p className="ed-form-note">{en?'Only C33 stories and magazine updates.':'仅用于接收 C33 新内容与刊物消息。'}</p><p role="status">{status}</p></div>;
}
