import {notFound} from 'next/navigation';
import type {Metadata} from 'next';
import Shell from '@/components/edition/Shell';
import {Home,CategoryPage,ReadPage,ArchivePage,ArchiveRead,TopicPage,SearchPage,SavedPage,InfoPage} from '@/components/edition/Pages';
import {getStories,getArchive} from '@/lib/edition/content';
import {categoryNames,type Category,type Locale} from '@/lib/edition/types';
import './edition.css';
type Props={params:{locale:string;path?:string[]};searchParams:{q?:string|string[]}};
function localeOf(s:string):Locale{if(s!=='en'&&s!=='zh')notFound();return s;}
function resolve(params:Props['params']){const l=localeOf(params.locale),p=params.path||[],key=p.join('/'),en=l==='en';const story=p[0]==='read'&&p.length===2?getStories().find(s=>s.slug===p[1]):undefined;const archive=p[0]==='archive'&&p.length===2?getArchive().find(s=>s.slug===p[1]):undefined;const titles:Record<string,string>={'':en?'Fashion, art & culture':'时尚、艺术与文化',about:en?'About':'关于',contact:en?'Contact':'联系',legal:en?'Legal information':'法律信息',issues:en?'Issues':'期刊',archive:en?'All articles':'文章目录',topics:en?'Topics':'专题','topics/milan-ss27':en?'Milan Fashion Week':'米兰时装周',search:en?'Search':'搜索',saved:en?'Reading list':'收藏'};const category=Object.keys(categoryNames).includes(key)?key as Category:undefined;const title=story?.title[l]||archive?.title[l]||(category?categoryNames[category][l]:titles[key]);if(!title)notFound();return {l,p,key,story,archive,category,title};}
export function generateMetadata({params}:Props):Metadata{const r=resolve(params),url=`/${r.l}${r.key?'/'+r.key:''}`,description=r.story?.summary[r.l]||r.archive?.summary[r.l]||(r.l==='en'?'C33 is an independent magazine covering fashion, art and culture.':'C33 是一本关注时尚、艺术与文化的独立刊物。');return {title:r.title,description,robots:{index:process.env.VERCEL_ENV!=='preview'&&!['search','saved'].includes(r.key)&&!(r.l==='en'&&r.archive&&!r.archive.fullTranslation),follow:true},alternates:{canonical:url,languages:{en:`/en${r.key?'/'+r.key:''}`,'zh-CN':`/zh${r.key?'/'+r.key:''}`}},openGraph:{title:`${r.title} — C33`,description,url,locale:r.l==='en'?'en_GB':'zh_CN',alternateLocale:[r.l==='en'?'zh_CN':'en_GB'],type:r.story?'article':'website',images:r.story?.image?[{url:r.story.image,alt:r.story.alt?.[r.l]}]:[{url:'/logo-c33.png',alt:'C33'}],...(r.story?{publishedTime:r.story.date,modifiedTime:r.story.updated||r.story.date}: {})},twitter:{card:'summary_large_image',title:`${r.title} — C33`,description,images:[r.story?.image||'/logo-c33.png']}};}
export default function Edition({params,searchParams}:Props){const r=resolve(params);let body:React.ReactNode;if(r.story)body=<ReadPage s={r.story} l={r.l}/>;else if(r.archive)body=<ArchiveRead a={r.archive} l={r.l}/>;else if(r.category)body=<CategoryPage l={r.l} category={r.category}/>;else if(!r.key)body=<Home l={r.l}/>;else if(r.key==='archive')body=<ArchivePage l={r.l}/>;else if(r.key==='topics'||r.key==='topics/milan-ss27')body=<TopicPage l={r.l} index={r.key==='topics'}/>;else if(r.key==='search')body=<SearchPage l={r.l} q={typeof searchParams.q==='string'?searchParams.q:''}/>;else if(r.key==='saved')body=<SavedPage l={r.l}/>;else body=<InfoPage l={r.l} page={r.key}/>;return <Shell locale={r.l}>{body}</Shell>;}
