const fs=require('fs');const assert=require('node:assert/strict');
const base=process.env.C33_PREVIEW_URL||'http://127.0.0.1:3336';
const inventory=JSON.parse(fs.readFileSync('docs/content-inventory.json','utf8'));
const routes=['','fashion','culture','people','about','contact','legal','issues','archive','topics','topics/milan-ss27','search','saved',...['marni-colour-off-centre','song-weilong-gucci-departure','tres-parisien-in-print','after-quiet-luxury','two-windows'].map(s=>'read/'+s),...inventory.map(s=>'archive/'+s.slug)];
const legacy=['/','/about','/contact','/mentions-legales','/journal','/issues','/lexique','/medias','/manifeste','/pitch','/contributeurs','/issue/01','/issue/02',...['mode','art-design','culture','villes','chroniques'].map(s=>'/category/'+s),...inventory.map(s=>s.original)];
const pending=[...new Set([...legacy,...['en','zh'].flatMap(l=>routes.map(p=>'/'+l+(p?'/'+p:'')))])];
const results=[];async function worker(){while(pending.length){const route=pending.shift();const r=await fetch(base+route);const html=await r.text();assert.equal(r.status,200,route);if(/^\/(en|zh)(\/|$)/.test(route)){if(process.env.C33_EXPECT_PREVIEW==='1')assert(html.includes('noindex'),route+' preview noindex');assert(html.includes('hrefLang="en"')||html.includes('hreflang="en"'),route+' alternate EN');assert(html.includes('hrefLang="zh-CN"')||html.includes('hreflang="zh-CN"'),route+' alternate ZH');assert(html.includes('id="edition-main"'),route+' content');}results.push({route,status:r.status});}}
(async()=>{await Promise.all(Array.from({length:4},worker));for(const route of ['/en/no-such-page','/en/read/missing-story','/zh/archive/missing-story','/de']){const r=await fetch(base+route);assert.equal(r.status,404,route);results.push({route,status:404});}
for(const [q,needle] of [['宋威龙','song-weilong-gucci-departure'],['Marni','marni-colour-off-centre']]){const h=await(await fetch(base+'/en/search?q='+encodeURIComponent(q))).text();assert(h.includes('/en/read/'+needle));}
const h=await(await fetch(base+'/en/search?q=nonexistentxyz')).text();assert(h.includes('No matching stories'));
fs.writeFileSync('docs/route-checks.json',JSON.stringify({checkedAt:new Date().toISOString(),base,total:results.length,results},null,2));console.log('PASS '+results.length+' route checks; localized metadata, bilingual search and empty search checked.');})().catch(e=>{console.error(e);process.exitCode=1});
